backend:
  name: git-gateway
  branch: main  # or master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
          - { label: "Welcome Text", name: "heroText", widget: "string" }
