backend:
  name: git-gateway
  branch: main


publish_mode: simple
media_folder: "images/uploads"      # Where uploaded files are stored
public_folder: "/images/uploads"    # URL path to uploaded files

collections:
  - name: "homepage"
    label: "Homepage Content"
    folder: "content/homepage"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
